postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=micodemo"
    - "POSTGRES_PASSWORD=micodemo"
  ports:
    - "5432:5432"

mico-serengeti-demo:
  dockerfile: Dockerfile.dev
  build: ./
  volumes:
    - ./:/rails_app
  ports:
    - "3000:80"
  environment:
    RAILS_ENV: development
  links:
    - postgres
